/* 시퀀스(SEQUENCE)
SEQUENCE : DB에서 제공하는 자동채번 객체
생성 : CREATE SEQUENCE 시퀀스명;
삭제 : DROP SEQUENCE 시퀀스명;

시퀀스명.NEXTVAL : 시퀀스 번호(값) 생성
시퀀스명.CURRVAL : 현재 시퀀스값 확인(NEXTVAL 사용 후)
****************************/
CREATE SEQUENCE SEQUENCE1;

CREATE SEQUENCE "MADANG"."SEQUENCE1"  
MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

-----------------
SELECT * FROM BOOK ORDER BY BOOKID DESC;

SELECT MAX(BOOKID), MAX(BOOKID) + 1 FROM BOOK;
SELECT MAX(BOOKID), NVL(MAX(BOOKID), 0) + 1 FROM BOOK;

CREATE TABLE AAA (ID NUMBER);
SELECT * FROM AAA;
SELECT MAX(ID), MAX(ID) + 1 FROM AAA; --데이터가 없을 때 MAX 값 NULL
SELECT MAX(ID), NVL(MAX(ID), 0) + 1 FROM AAA;
----------------
--시퀀스 사용
SELECT SEQUENCE1.NEXTVAL FROM DUAL;
SELECT SEQUENCE1.CURRVAL FROM DUAL;
-----------------
--BOOK 테이블에 INSERT 작업, BOOKID 최대값 + 1
INSERT INTO BOOK
       (BOOKID, BOOKNAME, PUBLISHER, PRICE)
VALUES ((SELECT NVL(MAX(BOOKID), 0) + 1 FROM BOOK), 
       'MAX(BOOKID)+1 값', 'IT_BOOK', 20000);       
SELECT * FROM BOOK ORDER BY BOOKID DESC;

--------------------
-- 시퀀스 사용(시작번호 50, NOCACHE)
CREATE SEQUENCE SEQ_BOOK
START WITH 50
INCREMENT BY 1
NOCACHE;
-----------------
--시퀀스 사용 : SEQ_BOOK.NEXTVAL
INSERT INTO BOOK
       (BOOKID, BOOKNAME, PUBLISHER, PRICE)
VALUES (SEQ_BOOK.NEXTVAL, 
       'SEQ_BOOK.NEXTVAL 사용', 'IT_BOOK', 25000);  
COMMIT;
SELECT * FROM BOOK ORDER BY BOOKID DESC;


